apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: gbadb
spec:
  openshift: true
  # this block is useful only if you also have monitoring set up for your cluster.
  # this example installation is intended to be as small as possible, so it has been removed.
  # however, this block remains as an example if you would like to add monitoring to your cluster.
  #
  # monitoring:
  #   pgmonitor:
  #     # this stuff is for the "exporter" container in the "gbadb-pg1" set of pods
  #     exporter:
  #       resources:
  #         requests:
  #           cpu: 50m
  #           memory: 32Mi
  #         limits:
  #           cpu: 100m
  #           memory: 64Mi
  postgresVersion: 15
  postGISVersion: "3.3"
  image: artifacts.developer.gov.bc.ca/bcgov-docker-local/crunchy-postgres-gis:ubi8-15.2-3.3-0
  imagePullPolicy: IfNotPresent
  instances:
    - name: pg1
      replicas: 3
      minAvailable: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 512Mi
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: 50m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 9Gi
        storageClassName: netapp-block-standard
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: gbadb
                  postgres-operator.crunchydata.com/instance-set: pg1
  bootstrap:
    postgresql:
      pg_hba:
#          - "host all all 0.0.0.0/0 trust" # this line enabled logical replication with programmatic access
        - "host all all all md5"
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
#          - "host all all 0.0.0.0/0 trust" # this line enabled logical replication with programmatic access
          - "host all all all md5"
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "2"
      repos:
      - name: repo1
        schedules:
          # Full backup every day at 8:00am UTC
          full: "0 8 * * *"
          # Incremental backup every 4 hours, except at 8am UTC (when the full backup is running)
          incremental: "0 0,4,12,16,20 * * *"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 512Mi
            storageClassName: netapp-file-backup
      repoHost:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      jobs:
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
      restore:
        repoName: repo1
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
      sidecars:
        pgbackrest:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        pgbackrestConfig:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      manual:
        repoName: repo1
        options:
         - --type=full
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          shared_buffers: '16MB'
          wal_buffers: '-1'
          min_wal_size: '32MB'
          max_wal_size: '64MB'
  proxy:
    pgBouncer:
      config:
        global:
          client_tls_sslmode: disable
      replicas: 2
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: gbadb
                  postgres-operator.crunchydata.com/role: pgbouncer
