apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: gba
spec:
  openshift: true
  instances:
    - name: pg1
      replicas: 3
      minAvailable: 1
      resources:
        requests:
          cpu: 250m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: 50m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
        storageClassName: netapp-block-standard
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "1"
      repos:
      - name: repo1
        schedules:
          full: "0 */4 * * *"
          incremental: "0 1-3,5-7,9-11,13-15,17-19,21-23 * * *"
        s3:
          endpoint: nrs.objectstore.gov.bc.ca
          bucket: rznpcz
          region: bc
      repoHost:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      jobs:
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
      restore:
        repoName: repo1
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
      sidecars:
        pgbackrest:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        pgbackrestConfig:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
  proxy:
    pgBouncer:
      replicas: 1
      minAvailable: 0
      resources:
        requests:
          cpu: 25m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 64Mi
