apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: da4d0e-test

secretGenerator:
- name: gbatest-pgbackrest-s3-creds
  files:
  - s3.conf

generatorOptions:
  disableNameSuffixHash: true

resources:
- PostgresCluster.yaml
#- TransportServerClaim.yaml
#- NetworkPolicy.yaml
