apiVersion: porter.devops.gov.bc.ca/v1alpha1
kind: TransportServerClaim
metadata:
  name: gbatest
spec:
  monitor:
    interval: 10
    timeout: 10
    type: tcp
  service: gbatest-pgbouncer
  servicePort: 5432
  