apiVersion: porter.devops.gov.bc.ca/v1alpha1
kind: TransportServerClaim
metadata:
  name: gba
spec:
  monitor:
    interval: 10
    timeout: 10
    type: tcp
  service: gba-pgbouncer
  servicePort: 5432
  